### PR TITLE
feat: add address to the `messageToFrameData`

### PR DESCRIPTION
**Pull request by dalechyn**
Ref: https://github.com/farcasterxyz/hub-monorepo/pull/1807

Added `address` to `FrameData`. Read more at https://warpcast.com/horsefacts.eth/0xb98e17d8.

### CODE REVIEW

**Comment by jxom** [comment]
Tysfm, and yeah, we need to regenerate the protobufs.

**Comment by dalechyn** [comment]
> Tysfm, and yeah, we need to regenerate the protobufs.

on it

**Comment by dalechyn** [comment]
@jxom I left `address` as type of `string` and not `Address` as I'm not sure wether this will be always ETH addresses only (similarly to `transactionId` not being `0x${string}`.

**Comment by dalechyn** [comment]
https://warpcast.com/horsefacts.eth/0xb9e9a831

Thinking about this one, we probably want to have `address` to be only defined in the `frameData` if it’s a transaction route.

**Comment by dalechyn** [comment]
github is laggy, beware. just pushed a commit

**Comment by jxom** [comment]
Can we add to docs too pls?

**Comment by dalechyn** [comment]
Haven't tested it though, going to bed rn. Will test tomorrow if you won't frontrun me.

**Comment by dalechyn** [comment]
Would we actually want to have `address` to not be undefined?
Since it lives just in one place, in Transaction Context.

**Pull request merged**
