### PR TITLE
feat: open frames

### PR DESCRIPTION
**Pull request by dalechyn**
I tried to do as little API changes as possible and introduced a new foundational piece of Frog – a renderer.

I did not find it possible to impelement such as a middleware as middlewares can only set variables, but not intercept a response to inject something.

### CODE REVIEW

**Comment by dalechyn** [comment]
Needs testing

**Comment by dalechyn** [comment]
Tested in app.converse.xyz, frame works, but now since the frame payload is different, some fields in `FrameData` would be empty.

Here's an example of the incoming payload:

```ts
{
  "clientProtocol": "xmtp@2024-02-09",
  "untrustedData": {
    "buttonIndex": 1,
    "opaqueConversationIdentifier": "uSt2VrxsWJZ+rOxtUIEyd9ZXSmKXxBdkFHQQGpMO70c=",
    "walletAddress": "0x94e54AC232042Bd6f416ad2F3637dBfe258509Fa",
    "inputText": "",
    "url": "https://f337-91-227-182-2.ngrok-free.app/open-frame",
    "timestamp": 1714495320464,
    "unixTimestamp": 1714495320464
  },
  "trustedData": {
    "messageBytes": "CkQKQgpA0dx77EMuCepz4qYytvjgTygxfD+Nok8ZGMrNk4y2HRV/bKCI4bfJrWCacldkV0bHKHzaHl//sQ6W/9uV8ppigxKwAgqUAQpMCOXapf7yMRpDCkEEb9n8qtfz4r95Ah8ay9/KQM48GZXjsq2dopMWBtMCGAox1nF3YOj0eVANSc9qxALGSlvp82RaYvlk/SFWbmPoJhJEEkIKQFFpM2ttlveGHkxy7H6NIbweR45I/lTQd8UKh5G+zxXrTgN4udZ8YBvG4mbTBljHuCvhm9llN3GV3HaSiLKkdxUSlgEKTAj37qX+8jEaQwpBBJ9T0grjDN+N71ZoHYjw9yLq7XZvnCRqft6fT144Ua4YU8KJYWTFqat3SSwtbEbXMHwgRcOdgAtmvibQPGbmbQISRgpECkDBFDnphWXzOz7288+a3FuGPOy8L2UiBM9qmhmn9LEcvTp7haxIbldmxdLOkdDzcgLLY+OgKKuxIR9VFFCfaxnTEAEacgozaHR0cHM6Ly9mMzM3LTkxLTIyNy0xODItMi5uZ3Jvay1mcmVlLmFwcC9vcGVuLWZyYW1lEAEYkOOJ//IxIix1U3QyVnJ4c1dKWityT3h0VUlFeWQ5WlhTbUtYeEJka0ZIUVFHcE1PNzBjPSiQ44n/Ag=="
  }
}
```

@jxom, can't see to get this working with the existing API, the only approach I could suggest is creating an `.openFrame` handler that would have different `FrameData` -> `OpenFrameData`.

it's also worth researching if such payloads can differ or not

**Comment by tmm** [comment]
Does this approach not work? https://github.com/wevm/frog/discussions/51#discussioncomment-8914766

Not sure this is worth adding until the Farcaster team bumps the Frames Spec to v1 at the least.

**Comment by dalechyn** [comment]
> Does this approach not work? [#51 (reply in thread)](https://github.com/wevm/frog/discussions/51#discussioncomment-8914766)

Doesn't seem like this one actually inserts `of:*` meta tags, and I think assigning to `c.res` is gonna override the previous frame response, so that a frame would only be compatible with `xmtp` in this case, but not compatible with FC.

> Not sure this is worth adding until the Farcaster team bumps the Frames Spec to v1 at the least.

that sounds fair as OF implementation may change along with the upcoming v1 spec which would result in re-implementing this PR, probably worth asking @horsefacts if this is in the near plans or not.

**Comment by humanagent** [comment]
Hey @dalechyn thanks for your contributions and making this possible!. Frog has now added [support](https://frog.fm/concepts/middleware#xmtp-frames-middleware) for XMTP Frames thanks to [tmm](https://github.com/tmm) [release 0.9.2](https://github.com/wevm/frog/releases/tag/frog%400.9.2) that adds support for custom header metadata.

**Pull request closed without merging**
